server:
  port: 8080

spring:
  profiles:
    active: local
  application:
    name: member
  dataSource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: Dlwngml12!

  security:
    user:
      name: user
      password: 1234
