server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    member:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: root
      password: tpdms10915
    payment:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/payment
      username: root
      password: tpdms10915
