server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    member:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/member
      username: root
      password: Dlwngml12!
    payment:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/payment
      username: root
      password: Dlwngml12!
  logging:
    level:
      root: INFO
      com.example.YourClass: DEBUG
