server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Dlwngml12!
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

logging:
  level:
    root: INFO
    com.example: DEBUG



